# Generated by Django 2.2.3 on 2022-04-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='examtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('question', models.CharField(default='', max_length=50)),
                ('answer', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'examtest',
            },
        ),
        migrations.CreateModel(
            name='MarksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=500)),
                ('marks', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'MarksTable',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=40)),
                ('mobileno', models.CharField(default='', max_length=50)),
                ('qualification', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=50)),
                ('status', models.CharField(default='', max_length=40)),
            ],
            options={
                'db_table': 'userregister',
            },
        ),
        migrations.CreateModel(
            name='UserTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=500, unique=True)),
                ('question1', models.CharField(default='', max_length=500)),
                ('answer1', models.CharField(default='', max_length=500)),
                ('question2', models.CharField(default='', max_length=500)),
                ('answer2', models.CharField(default='', max_length=500)),
                ('question3', models.CharField(default='', max_length=500)),
                ('answer3', models.CharField(default='', max_length=500)),
                ('question4', models.CharField(default='', max_length=500)),
                ('answer4', models.CharField(default='', max_length=500)),
                ('question5', models.CharField(default='', max_length=500)),
                ('answer5', models.CharField(default='', max_length=500)),
                ('question6', models.CharField(default='', max_length=500)),
                ('answer6', models.CharField(default='', max_length=500)),
                ('question7', models.CharField(default='', max_length=500)),
                ('answer7', models.CharField(default='', max_length=500)),
                ('question8', models.CharField(default='', max_length=500)),
                ('answer8', models.CharField(default='', max_length=500)),
                ('question9', models.CharField(default='', max_length=500)),
                ('answer9', models.CharField(default='', max_length=500)),
                ('question10', models.CharField(default='', max_length=500)),
                ('answer10', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'UserTestTable',
            },
        ),
    ]
